# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
    
    runs-on: windows-latest

    env:
      Solution_Name: GZSkinsX.sln
      Appx_Project_Path: src\appx\GZSkinsX\GZSkinsX.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v3      
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2  

    - name: Restore
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Build
      run: msbuild $env:Appx_Project_Path /p:Configuration=$env:Configuration 
      env:
        Appx_Bundle_Platforms: x86|x64
        Configuration: ${{ matrix.configuration }}
